---
# Per environment values which override defaults in hmpps-manage-offences/values.yaml

generic-service:

  ingress:
    host: manage-offences.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-offences.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
